import base from '@typeflowjs/lint-config/oxfmt';
import { defineConfig } from 'oxfmt';

export default defineConfig({
  ...base,
  ignorePatterns: [
    '**/node_modules/**',
    '.vitepress/dist/**',
    '.vitepress/cache/**',
    // Generated by scripts/generate-docs.ts / the benchmarks publish step.
    'operators/**',
    'functions/**',
    'migration/**',
    'reference/**',
    'fr/operators/**',
    'fr/functions/**',
    'fr/migration/**',
    'fr/reference/**',
    'benchmarks/**',
  ],
});
